### PR TITLE
Use @latest for CodeSandbox SDK includes

### PR DESCRIPTION
**Pull request by AndrewDiMola**
Per https://developer.grammarly.com/docs/releases#adding-the-sdk-with-an-npm-package. use `@latest` for SDK `<script>` includes.

### CODE REVIEW

**Comment by AndrewDiMola** [comment]
Looks like @znck already found one of these and made an update: https://github.com/grammarly/grammarly-for-developers/commit/9cdeaf164c41d949175abbb64a0558061298c1fd

Any significant difference between using `@latest` and dropping it altogether?

**Review by znck — APPROVED** [review]

**Comment by ljhaywar** [comment]
I remember David saying something about caching issues in CodeSandbox if we didn't specify the version. @wachunga do you remember this? 

Let's keep an eye out to ensure the examples continue to work after the next release.

**Comment by AndrewDiMola** [comment]
@ljhaywar - Doing a few spot checks but seems to be OK.

https://github.com/grammarly/grammarly-for-developers/tree/main/examples/editor-sdk

image

**Comment by ljhaywar** [comment]
Fabulous! Thanks for checking on this!

**Pull request merged**
